# Generated by Django 4.2.18 on 2025-01-16 13:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('conta', models.CharField(max_length=20)),
                ('agencia', models.CharField(max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tipodeconta', models.CharField(choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], default='corrente', max_length=50)),
                ('conta_pix', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(choices=[('comum', 'Comum'), ('especial', 'Especial')], default='comum', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
                ('cpf', models.CharField(max_length=18)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('inscricao_municipal', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('complemtento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=50)),
                ('agencia', models.CharField(max_length=50)),
                ('conta', models.CharField(max_length=50)),
                ('tipodeconta', models.CharField(max_length=50)),
                ('conta_pix', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('Fornecedor', 'Fornecedor'), ('Socio', 'Socio'), ('Funcionario', 'Funcionario')], default='Fornecedor', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pagador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
                ('cpf', models.CharField(max_length=18)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('inscricao_municipal', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('complemtento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=50)),
                ('agencia', models.CharField(max_length=50)),
                ('conta', models.CharField(max_length=50)),
                ('tipodeconta', models.CharField(max_length=50)),
                ('conta_pix', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('Cliente', 'Cliente'), ('Socio', 'Socio')], default='Cliente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_transferencia', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('responsavel', models.CharField(choices=[('VIP ADVISER', 'VIP ADVISER'), ('VIP ECO', 'VIP ECO'), ('VIP EARTH', 'VIP EARTH'), ('VIP RETY', 'VIP RETY')], default='VIP ADVISER', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('transferido', 'Transferido')], default='pendente', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='transferencias/')),
                ('banco_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='core.banco')),
                ('banco_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origem', to='core.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_prevista', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido')], default='pendente', max_length=20)),
                ('metodo_pagamento', models.CharField(choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('cheque', 'Cheque')], default='pix', max_length=20)),
                ('responsavel', models.CharField(choices=[('VIP ADVISER', 'VIP ADVISER'), ('VIP ECO', 'VIP ECO'), ('VIP EARTH', 'VIP EARTH'), ('VIP RETY', 'VIP RETY')], default='VIP ADVISER', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='recebimentos/')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.banco')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.centrocusto')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='core.pagador')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_prevista', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20)),
                ('responsavel', models.CharField(choices=[('VIP ADVISER', 'VIP ADVISER'), ('VIP ECO', 'VIP ECO'), ('VIP EARTH', 'VIP EARTH'), ('VIP RETY', 'VIP RETY')], default='VIP ADVISER', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='pagamentos/')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.banco')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.centrocusto')),
                ('favorecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.favorecido')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_novo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.banco')),
            ],
        ),
    ]
